const questions = [
  {
    id: 1,
    text: "我花费很多闲暇时间学习各种新事物（而不是做其他事情），主要目的是为了积累更多知识（尽管这些知识在实际中可能并无太多用处）",
    name: "curiosity1",
    type: "radio",
    options: [
      { optionId: 1, value: "非常不符合", score: -3 },
      { optionId: 2, value: "比较不符合", score: -2 },
      { optionId: 3, value: "略微不符合", score: -1 },
      { optionId: 4, value: "略微符合", score: 1 },
      { optionId: 5, value: "比较符合", score: 2 },
      { optionId: 6, value: "非常符合", score: 3 },
    ],
  },
  {
    id: 2,
    text: "【会忍不住去理解以及搞清楚一套复杂的事物，并给予合理的解释】还是【享受生活和现实，给什么东西都复杂的解释和抽象、太累了】更倾向于支持哪一个？",
    name: "curiosity2",
    type: "radio",
    options: [
      { optionId: 1, value: "非常倾向于前者", score: -3 },
      { optionId: 2, value: "比较倾向于前者", score: -2 },
      { optionId: 3, value: "略微倾向于前者", score: -1 },
      { optionId: 4, value: "略微倾向于后者", score: 1 },
      { optionId: 5, value: "比较倾向于后者", score: 2 },
      { optionId: 6, value: "非常倾向于后者", score: 3 },
    ],
  },
  {
    id: 3,
    text: "你看的书多吗？",
    name: "readly",
    type: "radio",
    options: [
      { optionId: 1, value: "从不看书，对看书不感兴趣", score: 0 },
      {
        optionId: 2,
        value: "偶尔看书，看的不多，三四个月一本书或更少",
        score: 2,
      },
      { optionId: 3, value: "有长期阅读的习惯，一个月一本左右", score: 4 },
      { optionId: 4, value: "重度阅读者，每个月两三本书或更多", score: 6 },
    ],
  },
  {
    id: 4,
    text: "当讨论变得高度理论化时（比如科学理论、哲学社会学概念、数学内容等等），你会觉得无聊或者失去兴趣。",
    name: "abstractness1",
    type: "radio",
    options: [
      { optionId: 1, value: "非常不符合", score: -3 },
      { optionId: 2, value: "比较不符合", score: -2 },
      { optionId: 3, value: "略微不符合", score: -1 },
      { optionId: 4, value: "略微符合", score: 1 },
      { optionId: 5, value: "比较符合", score: 2 },
      { optionId: 6, value: "非常符合", score: 3 },
    ],
  },
  {
    id: 5,
    text: "你更希望能和对方交流具体实在、务实的，比如衣食住行，吃喝玩乐的日常内容还是更加抽象的概念理论，比如哲学、心理学、社会学、科学原理等等。",
    name: "abstractness2",
    type: "radio",
    options: [
      { optionId: 1, value: "非常倾向于前者，无法接受不这样的", score: -3 },
      { optionId: 2, value: "比较倾向于前者，会增加较多好感", score: -2 },
      { optionId: 3, value: "略微倾向于前者，会增加略微好感", score: -1 },
      { optionId: 4, value: "中立无所谓，你不在乎", score: 0 },
      { optionId: 5, value: "略微倾向于后者，会增加略微好感", score: 1 },
      { optionId: 6, value: "比较倾向于后者。会增加较多好感", score: 2 },
      { optionId: 7, value: "非常倾向于后者，无法接受不这样的", score: 3 },
    ],
  },
  {
    id: 6,
    text: "你是否很乐意花费大量的时间用来解决复杂的智力问题，也喜欢智力上的挑战。比如解决困难的数学题，学习晦涩难懂的物理、经济、哲学理论。",
    name: "intellectual",
    type: "radio",
    options: [
      { optionId: 1, value: "非常不符合", score: -3 },
      { optionId: 2, value: "比较不符合", score: -2 },
      { optionId: 3, value: "略微不符合", score: -1 },
      { optionId: 4, value: "略微符合", score: 1 },
      { optionId: 5, value: "比较符合", score: 2 },
      { optionId: 6, value: "非常符合", score: 3 },
    ],
  },
  {
    id: 7,
    text: "您经常花很多时间试图理解与您自己截然不同的观点。",
    name: "openl1",
    type: "radio",
    options: [
      { optionId: 1, value: "非常不符合", score: -3 },
      { optionId: 2, value: "比较不符合", score: -2 },
      { optionId: 3, value: "略微不符合", score: -1 },
      { optionId: 4, value: "略微符合", score: 1 },
      { optionId: 5, value: "比较符合", score: 2 },
      { optionId: 6, value: "非常符合", score: 3 },
    ],
  },
  {
    id: 8,
    text: "让学生们听富有争议性的演讲只会混淆和误导他们的思想，比如日本核废水、中医、特斯拉刹车失灵、西方价值观等敏感议题。",
    name: "openl2",
    type: "radio",
    options: [
      { optionId: 1, value: "非常不赞同", score: 3 },
      { optionId: 2, value: "比较不赞同", score: 2 },
      { optionId: 3, value: "略微不赞同", score: 1 },
      { optionId: 4, value: "略微赞同", score: -1 },
      { optionId: 5, value: "比较赞同", score: -2 },
      { optionId: 6, value: "非常赞同", score: -3 },
    ],
  },
  {
    id: 9,
    text: "相比熟悉事物带来的安全感，你是否更加愿意尝试新的事物，也愿意主动追求新奇的体验。无论是游戏、电影电视剧、还是吃喝玩乐、探险旅游之类的。",
    name: "tryNew1",
    type: "radio",
    options: [
      { optionId: 1, value: "非常不符合", score: -3 },
      { optionId: 2, value: "比较不符合", score: -2 },
      { optionId: 3, value: "略微不符合", score: -1 },
      { optionId: 4, value: "略微符合", score: 1 },
      { optionId: 5, value: "比较符合", score: 2 },
      { optionId: 6, value: "非常符合", score: 3 },
    ],
  },
  {
    id: 10,
    text: "你是否有很多兴趣爱好，也对各种事物都充满兴趣，想去接触了解。",
    name: "tryNew2",
    type: "radio",
    options: [
      { optionId: 1, value: "非常不符合", score: -3 },
      { optionId: 2, value: "比较不符合", score: -2 },
      { optionId: 3, value: "略微不符合", score: -1 },
      { optionId: 4, value: "略微符合", score: 1 },
      { optionId: 5, value: "比较符合", score: 2 },
      { optionId: 6, value: "非常符合", score: 3 },
    ],
  },
  {
    id: 11,
    text: "你是否对社会公共议题（如教育、医疗、司法公正、人均收入等）不感兴趣，更关注个人的生活和发展？",
    name: "idea1",
    type: "radio",
    options: [
      { optionId: 1, value: "非常不符合", score: 3},
      { optionId: 2, value: "比较不符合", score: 2 },
      { optionId: 3, value: "略微不符合", score: 1 },
      { optionId: 4, value: "略微符合", score: -1 },
      { optionId: 5, value: "比较符合", score: -2 },
      { optionId: 6, value: "非常符合", score: -3 },
    ],
  },
  {
    id: 12,
    text: "是否对于道德伦理、人格以及价值观之类的话题并没有过多的兴趣也没有坚定的立场，更关注个人的生活和发展？",
    name: "idea2",
    type: "radio",
    options: [
      { optionId: 1, value: "非常不符合", score: 3 },
      { optionId: 2, value: "比较不符合", score: 2 },
      { optionId: 3, value: "略微不符合", score: 1 },
      { optionId: 4, value: "略微符合", score: -1 },
      { optionId: 5, value: "比较符合", score: -2 },
      { optionId: 6, value: "非常符合", score: -3 },
    ],
  },
  {
    id: 13,
    text: "在人生的重要问题决策上（婚姻、就业）上，即使和自己的意愿相违背，你也会服从父母和老师等人的安排，因为你不愿意和他们发生冲突或者不愿意让他们失望。",
    name: "standard1",
    type: "radio",
    options: [
      { optionId: 1, value: "非常不符合", score: 3 },
      { optionId: 2, value: "比较不符合", score: 2 },
      { optionId: 3, value: "略微不符合", score: 1 },
      { optionId: 4, value: "略微符合", score: -1 },
      { optionId: 5, value: "比较符合", score: -2 },
      { optionId: 6, value: "非常符合", score: -3 },
    ],
  },
  {
    id: 14,
    text: "你是否非常认可你自己的价值和能力，且不会被他人的评价和批评影响到自己的价值感和自尊心。",
    name: "standard2",
    type: "radio",
    options: [
      { optionId: 1, value: "非常不符合", score: 3 },
      { optionId: 2, value: "比较不符合", score: 2 },
      { optionId: 3, value: "略微不符合", score: 1 },
      { optionId: 4, value: "略微符合", score: -1 },
      { optionId: 5, value: "比较符合", score: -2 },
      { optionId: 6, value: "非常符合", score: -3 },
    ],
  },
  {
    id: 15,
    text: "你是否讨厌那些表达出亲欧美社会、亲西方价值观的人？",
    name: "attitudes",
    type: "radio",
    options: [
      { optionId: 1, value: "非常不符合", score: 6 },
      { optionId: 2, value: "比较不符合", score: 4 },
      { optionId: 3, value: "略微不符合", score: 2 },
      { optionId: 4, value: "略微符合", score: -2 },
      { optionId: 5, value: "比较符合", score: -4 },
      { optionId: 6, value: "非常符合", score: -6 },
    ],
  },
  {
    id: 16,
    text: "在看到一个人在虐待流浪猫时，你会倾向于？",
    name: "hc",
    type: "radio",
    options: [
      { optionId: 1, value: "上前阻止，你不支持虐待动物", score: 6 },
      {
        optionId: 2,
        value: "远远看着，但你内心反对虐猫，也反对这一行为。",
        score: 0
      },
      { optionId: 3, value: "远远看着，且你内心并不反对这一行为。", score: -6 },
    ],
  },
  {
    id: 17,
    text: "你是否相信风水，认可风水可以解释很多东西。",
    name: "fs",
    type: "radio",
    options: [
      { optionId: 1, value: "非常不相信", score: -6 },
      { optionId: 2, value: "比较不相信", score: -4 },
      { optionId: 3, value: "略微不相信", score: -2 },
      { optionId: 4, value: "略微相信", score: 2 },
      { optionId: 5, value: "比较相信", score: 4 },
      { optionId: 6, value: "非常相信", score: 6 },
    ],
  },
  {
    id: 18,
    text: "相比参加人多的聚会，你是否更喜欢和两三个亲密的朋友在一起。",
    name: "characterl1",
    type: "radio",
    options: [
      { optionId: 1, value: "非常不符合", score: -3 },
      { optionId: 2, value: "比较不符合", score: -2 },
      { optionId: 3, value: "略微不符合", score: -1 },
      { optionId: 4, value: "略微符合", score: 1 },
      { optionId: 5, value: "比较符合", score: 2 },
      { optionId: 6, value: "非常符合", score: 3 },
    ],
  },
  {
    id: 19,
    text: "你更倾向于在独处中还是身处在人群里、参加聚会来获取精神能量（感到充满活力和动力）？",
    name: "characterl2",
    type: "radio",
    options: [
      { optionId: 1, value: "非常倾向于前者", score: 3 },
      { optionId: 2, value: "比较倾向于前者", score: 2 },
      { optionId: 3, value: "略微倾向于前者", score: 1 },
      { optionId: 4, value: "略微倾向于后者", score: -1 },
      { optionId: 5, value: "比较倾向于后者", score: -2 },
      { optionId: 6, value: "非常倾向于后者", score: -3 },
    ],
  },
  {
    id: 20,
    text: "你是否很在意保持生活或者工作环境的整洁和有序？经常清理和整理物品和空间。",
    name: "organization1",
    type: "radio",
    options: [
      { optionId: 1, value: "非常不符合", score: -3 },
      { optionId: 2, value: "比较不符合", score: -2 },
      { optionId: 3, value: "略微不符合", score: -1 },
      { optionId: 4, value: "略微符合", score: 1 },
      { optionId: 5, value: "比较符合", score: 2 },
      { optionId: 6, value: "非常符合", score: 3 },
    ],
  },
  {
    id: 21,
    text: "你是一个做事很有条理的人",
    name: "organization2",
    type: "radio",
    options: [
      { optionId: 1, value: "非常不符合", score: -3 },
      { optionId: 2, value: "比较不符合", score: -2 },
      { optionId: 3, value: "略微不符合", score: -1 },
      { optionId: 4, value: "略微符合", score: 1 },
      { optionId: 5, value: "比较符合", score: 2 },
      { optionId: 6, value: "非常符合", score: 3 },
    ],
  },
  {
    id: 22,
    text: "在认知和做决策时，你更倾向于客观的事实、分析和数据还是感性的情感共鸣、个人感受、人情味、个人价值观。 ",
    name: "inductive",
    type: "radio",
    options: [
      { optionId: 1, value: "非常倾向于前者", score: 6 },
      { optionId: 2, value: "比较倾向于前者", score: 4 },
      { optionId: 3, value: "略微倾向于前者", score: 2 },
      { optionId: 4, value: "略微倾向于后者", score: -2 },
      { optionId: 5, value: "比较倾向于后者", score: -4 },
      { optionId: 6, value: "非常倾向于后者", score: -6 },
    ],
  },
  {
    id: 23,
    text: "只要成果大，你愿意冒险和承担失败的风险（比如高风险的投资和创业）",
    name: "adventure1",
    type: "radio",
    options: [
      { optionId: 1, value: "非常不符合", score: -3 },
      { optionId: 2, value: "比较不符合", score: -2 },
      { optionId: 3, value: "略微不符合", score: -1 },
      { optionId: 4, value: "略微符合", score: 1 },
      { optionId: 5, value: "比较符合", score: 2 },
      { optionId: 6, value: "非常符合", score: 3 },
    ],
  },
  {
    id: 24,
    text: "你更加倾向于哪一种生活？【稳定安逸、轻轻松松的生活】还是【紧张、富有挑战的生活】",
    name: "adventure2",
    type: "radio",
    options: [
      { optionId: 1, value: "非常倾向于前者", score: -3 },
      { optionId: 2, value: "比较倾向于前者", score: -2 },
      { optionId: 3, value: "略微倾向于前者", score: -1 },
      { optionId: 4, value: "略微倾向于后者", score: 1 },
      { optionId: 5, value: "比较倾向于后者", score: 2 },
      { optionId: 6, value: "非常倾向于后者", score: 3 },
    ],
  },
  {
    id: 25,
    text: "你是否非常渴望能做出一番事业或在自己所处的领域中成为顶尖人物？",
    name: "achievement1",
    type: "radio",
    options: [
      { optionId: 1, value: "非常不符合", score: -3 },
      { optionId: 2, value: "比较不符合", score: -2 },
      { optionId: 3, value: "略微不符合", score: -1 },
      { optionId: 4, value: "略微符合", score: 1 },
      { optionId: 5, value: "比较符合", score: 2 },
      { optionId: 6, value: "非常符合", score: 3 },
    ],
  },
  {
    id: 26,
    text: "对于平凡的一生是否值得过，你的态度是？",
    name: "achievement2",
    type: "radio",
    options: [
      {
        optionId: 1,
        value: "完全接受平凡的生活， 你也不介意成为一个平凡的人。",
        score: -3,
      },
      { optionId: 2, value: "比较接受", score: -2 },
      { optionId: 3, value: "略微接受", score: -1 },
      { optionId: 4, value: "略微不接受", score: 1 },
      { optionId: 5, value: "比较不接受", score: 2 },
      { optionId: 6, value: "完全不接受，你非常害怕成为平凡的人。", score: 3 },
    ],
  },
  {
    id: 27,
    text: "你很注重美感体验并常常沉醉其中吗？包括建筑设计，艺术画作，音乐等等，也喜欢去艺术馆之类的地方吗？ ",
    name: "aesthetic1",
    type: "radio",
    options: [
      { optionId: 1, value: "非常不符合", score: -3 },
      { optionId: 2, value: "比较不符合", score: -2 },
      { optionId: 3, value: "略微不符合", score: -1 },
      { optionId: 4, value: "略微符合", score: 1 },
      { optionId: 5, value: "比较符合", score: 2 },
      { optionId: 6, value: "非常符合", score: 3 },
    ],
  },
  {
    id: 28,
    text: "你是否对艺术不感兴趣，也没有这方面的兴趣爱好。",
    name: "aesthetic2",
    type: "radio",
    options: [
      { optionId: 1, value: "非常不符合", score: 3 },
      { optionId: 2, value: "比较不符合", score: 2 },
      { optionId: 3, value: "略微不符合", score: 1 },
      { optionId: 4, value: "略微符合", score: -1 },
      { optionId: 5, value: "比较符合", score: -2 },
      { optionId: 6, value: "非常符合", score: -3 },
    ],
  },
  {
    id: 29,
    text: "你是否是一个寻求刺激的人，喜欢看恐怖电影 飙车 跳伞 攀岩  滑翔  格斗 跑酷 之类的 能带来强烈兴奋感的活动。",
    name: "excitement1",
    type: "radio",
    options: [
      { optionId: 1, value: "非常不符合", score: -3 },
      { optionId: 2, value: "比较不符合", score: -2 },
      { optionId: 3, value: "略微不符合", score: -1 },
      { optionId: 4, value: "略微符合", score: 1 },
      { optionId: 5, value: "比较符合", score: 2 },
      { optionId: 6, value: "非常符合", score: 3 },
    ],
  },
  {
    id: 30,
    text: "你是否常常能在日常生活中的小事情、平凡的活动中感到满足愉悦和幸福（类似小确幸）。比如烹饪和享受美食、温暖阳关、爱宠陪伴、内心宁静等等。",
    name: "excitement2",
    type: "radio",
    options: [
      { optionId: 1, value: "非常不符合", score: 3 },
      { optionId: 2, value: "比较不符合", score: 2 },
      { optionId: 3, value: "略微不符合", score: 1 },
      { optionId: 4, value: "略微符合", score: -1 },
      { optionId: 5, value: "比较符合", score: -2 },
      { optionId: 6, value: "非常符合", score: -3 },
    ],
  },
  {
    id: 31,
    text: "你是否很少注意到自己在不同环境下的情绪和感受",
    name: "emotion1",
    type: "radio",
    options: [
      { optionId: 1, value: "非常不符合", score: -3 },
      { optionId: 2, value: "比较不符合", score: -2 },
      { optionId: 3, value: "略微不符合", score: -1 },
      { optionId: 4, value: "略微符合", score: 1 },
      { optionId: 5, value: "比较符合", score: 2 },
      { optionId: 6, value: "非常符合", score: 3 },
    ],
  },
  {
    id: 32,
    text: "你是否是一个情感细腻且丰富的人，喜欢感受自己内心的想法，也很乐意去感受文学作品、诗歌散文、艺术作品中包含的细腻情感。",
    name: "emotion2",
    type: "radio",
    options: [
      { optionId: 1, value: "非常不符合", score: -3 },
      { optionId: 2, value: "比较不符合", score: -2 },
      { optionId: 3, value: "略微不符合", score: -1 },
      { optionId: 4, value: "略微符合", score: 1 },
      { optionId: 5, value: "比较符合", score: 2 },
      { optionId: 6, value: "非常符合", score: 3 },
    ],
  },
  {
    id: 33,
    text: "你是否经常表现出对规则、限制的抵触情绪和逆反心理，比如不愿意遵守传统观念，也常常质疑和反对学校规定或者父母的意见。",
    name: "rebel1",
    type: "radio",
    options: [
      { optionId: 1, value: "非常不符合", score: -3 },
      { optionId: 2, value: "比较不符合", score: -2 },
      { optionId: 3, value: "略微不符合", score: -1 },
      { optionId: 4, value: "略微符合", score: 1 },
      { optionId: 5, value: "比较符合", score: 2 },
      { optionId: 6, value: "非常符合", score: 3 },
    ],
  },
  {
    id: 34,
    text: "权威（家长、公权力、老师等）总的来说应该被质疑还是服从和尊敬？",
    name: "rebel2",
    type: "radio",
    options: [
      { optionId: 1, value: "非常倾向于质疑", score: 3 },
      { optionId: 2, value: "比较倾向于质疑", score: 2 },
      { optionId: 3, value: "略微倾向于质疑", score: 1 },
      { optionId: 4, value: "略微倾向于服从和尊敬", score: -1 },
      { optionId: 5, value: "比较倾向于服从和尊敬", score: -2 },
      { optionId: 6, value: "非常倾向于服从和尊敬", score: -3 },
    ],
  },
  {
    id: 35,
    text: "你不太关心别人是否受到不公正的待遇。",
    name: "altruism1",
    type: "radio",
    options: [
      { optionId: 1, value: "非常不符合", score: 3 },
      { optionId: 2, value: "比较不符合", score: 2 },
      { optionId: 3, value: "略微不符合", score: 1 },
      { optionId: 4, value: "略微符合", score: -1 },
      { optionId: 5, value: "比较符合", score: -2 },
      { optionId: 6, value: "非常符合", score: -3 },
    ],
  },
  {
    id: 36,
    text: "日常生活中，即使没有直接的利益回报，你也愿意主动帮助他人？",
    name: "altruism2",
    type: "radio",
    options: [
      { optionId: 1, value: "非常不符合", score: -3 },
      { optionId: 2, value: "比较不符合", score: -2 },
      { optionId: 3, value: "略微不符合", score: -1 },
      { optionId: 4, value: "略微符合", score: 1 },
      { optionId: 5, value: "比较符合", score: 2 },
      { optionId: 6, value: "非常符合", score: 3 },
    ],
  },
  {
    id: 37,
    text: "当你所属的团体受到他人羞辱的时候，比如你所在的班级、小组、或者国家，你个人的自尊心和自我价值感是否会受到影响？",
    name: "selfish1",
    type: "radio",
    options: [
      {
        optionId: 1,
        value: "完全不会受到影响，你的自尊和价值感更多来自于你自己的内在。",
        score: 3,
      },
      { optionId: 2, value: "比较倾向于不会", score: 2 },
      { optionId: 3, value: "略微倾向于不会", score: 1 },
      { optionId: 4, value: "略微倾向于会受到影响", score: -1 },
      { optionId: 5, value: "比较倾向于会受到影响", score: -2 },
      {
        optionId: 6,
        value: "会受到很大的影响，你所在的群体对你来说意义很大。",
        score: -3,
      },
    ],
  },
  {
    id: 38,
    text: "对于集体的荣誉和成就，您是否有着强烈的归属感和自豪感？（比如会为华为公司感到发自内心的骄傲，或者为自己的班级的荣誉感到欣喜）",
    name: "selfish2",
    type: "radio",
    options: [
      { optionId: 1, value: "非常不符合", score: 3 },
      { optionId: 2, value: "比较不符合", score: 2 },
      { optionId: 3, value: "略微不符合", score: 1 },
      { optionId: 4, value: "略微符合", score: -1 },
      { optionId: 5, value: "比较符合", score: -2 },
      { optionId: 6, value: "非常符合", score: -3 },
    ],
  },
  {
    id: 39,
    text: "你是否赞同“相比发展自己的事业，女性应该学会洗衣做饭，承担家务，在婚姻后专注家庭”",
    name: "male1",
    type: "radio",
    options: [
      { optionId: 1, value: "非常不赞同", score: -3 },
      { optionId: 2, value: "比较不赞同", score: -2 },
      { optionId: 3, value: "略微不赞同", score: -1 },
      { optionId: 4, value: "略微赞同", score: 1 },
      { optionId: 5, value: "比较赞同", score: 2 },
      { optionId: 6, value: "非常赞同", score: 3 },
    ],
  },
  {
    id: 40,
    text: "在恋情中，你是否更希望对方是贤惠顾家，听话服从的。",
    name: "male2",
    type: "radio",
    options: [
      { optionId: 1, value: "非常不赞同", score: -3 },
      { optionId: 2, value: "比较不赞同", score: -2 },
      { optionId: 3, value: "略微不赞同", score: -1 },
      { optionId: 4, value: "略微赞同", score: 1 },
      { optionId: 5, value: "比较赞同", score: 2 },
      { optionId: 6, value: "非常赞同", score: 3 },
    ],
  },
];

export default questions;
